### ISSUE TITLE
How do we generate (or view, if they are being generated) log files?

### ISSUE THREAD

**Issue by olyerickson** [yesworkflow-org/yw-prototypes#33]
I'm seeing the following java error:

```
java.util.NoSuchElementException
	at java.util.StringTokenizer.nextToken(StringTokenizer.java:349)
	at org.yesworkflow.annotations.Annotation.<init>(Annotation.java:35)
	at org.yesworkflow.annotations.AliasableAnnotation.<init>(AliasableAnnotation.java:10)
	at org.yesworkflow.annotations.Flow.<init>(Flow.java:10)
	at org.yesworkflow.annotations.Out.<init>(Out.java:9)
	at org.yesworkflow.extract.DefaultExtractor.extractAnnotations(DefaultExtractor.java:305)
	at org.yesworkflow.extract.DefaultExtractor.extract(DefaultExtractor.java:169)
	at org.yesworkflow.extract.DefaultExtractor.extract(DefaultExtractor.java:43)
	at org.yesworkflow.cli.YesWorkflowCLI.extract(YesWorkflowCLI.java:371)
	at org.yesworkflow.cli.YesWorkflowCLI.runForArgs(YesWorkflowCLI.java:255)
	at org.yesworkflow.cli.YesWorkflowCLI.main(YesWorkflowCLI.java:90)
```

I suspect I've got a bad @something somewhere, but can't spot it...

Thanks!

**Comment by olyerickson** [comment]
Bug found --- missing @as --- but the question stands...

**Comment by ludaesch** [comment]
Since @as is optional, why is there ug when you're missing @as?
Did you have multiple names, such as "@in foo1 foo2" and meant to say "@in
foo1 @as foo2" ?
Note that "@in foo bar baz" might be an allowed shortcut in the future (for
3 @in statements..)

**Comment by tmcphillips** [comment]
The exception you reported occurs when a YW keyword is not followed by an argument, e.g. a comment containing only the following triggers this exception and the long stack trace:
```
@begin
```
I just pushed a commit to the repo that makes YW produce a more informative message.  With this change the above erroneous YW annotation produces a result such as the following at the command line:
```
$ yw graph
******************* YESWORKFLOW MARKUP ERRORS **************************
No argument provided to @begin keyword on line 9
------------------------------------------------------------------------
$ 

```
Is this consistent with the bug you found in your YW markup?
